service: ats-microservice

provider:
  name: aws
  runtime: python3.9

plugins:
  - serverless-offline

functions:

  getJobs:
    handler: handler.list_jobs
    events:
      - http:
          path: jobs
          method: get

  createCandidate:
    handler: handler.post_candidate
    events:
      - http:
          path: candidates
          method: post

  getApplications:
    handler: handler.list_applications
    events:
      - http:
          path: applications
          method: get

  